import {StyleSheet} from 'react-native';

export const Quiz_Screen_Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  TitleOnTopView: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  TitleOnTopTextStyle: {
    fontSize: 30,
    // color: '#58C4DC',
    fontFamily: 'Poppins-Bold',
  },
  ScrollView_ContentContainerStyle: {flex: 1, padding: 10},
  ProgressBarView: {
    paddingTop: 45,
  },
  Question_View: {
    padding: 5,
    marginBottom: 5,
  },
  Question_Text_Style: {
    fontSize: 16,
    color: 'black',
    fontWeight: '500',
    fontFamily: 'Montserrat-SemiBold',
  },
  Options_View: {
    marginTop: 5,
  },
  defaultOptionButtonStyle: {
    height: 60,
    borderRadius: 8,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    marginLeft: 30,
    backgroundColor: 'white',
    borderColor: 'rgba(0, 0, 0, 0.2)',
  },
  correctOptionButtonStyle: {
    height: 60,
    borderRadius: 8,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    marginLeft: 30,
    backgroundColor: '#C7FFB7',
    borderColor: 'rgba(199, 255, 183, 0.2)',
  },
  wrongOptionButtonStyle: {
    height: 60,
    borderRadius: 8,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    marginLeft: 30,
    backgroundColor: '#FFC5B2',
    borderColor: 'rgba(250, 0, 0, 0.2)',
  },
  Options_Text_Style: {
    color: 'black',
    fontSize: 16,
  },
  Explanation_ContinueButton_View: {
    flex: 1,
    justifyContent: 'center',
    marginTop: 10,
  },
  correctAnswerExplanation: {
    flex: 3,
    padding: 10,
    height: 'auto',
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#C7FFB7',
    borderColor: 'rgba(147, 250, 165, 0.8)',
  },
  wrongAnswerExplanation: {
    flex: 3,
    height: 'auto',
    padding: 10,
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 8,
    backgroundColor: '#FFC5B2',
    borderColor: 'rgba(250, 0, 0, 0.2)',
  },
  defaultExplanationView: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  BulletPointStyle: {
    color: 'black',
    fontSize: 20,
  },
  ExplanationTextStyle: {
    color: 'black',
    fontSize: 16,
  },
  ContinueButtonView: {
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 10,
  },
  ReferenceLinkStyle: {
    color: 'blue',
    textDecorationLine: 'underline',
  },
  continueButtonIfCorrect: {
    height: 70,
    width: '100%',
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    backgroundColor: '#6FE427',
    borderRadius: 8,
    borderColor: 'rgba(111, 228, 39, 0.8)',
  },
  continueButtonIfWrong: {
    height: 70,
    width: '100%',
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    backgroundColor: '#FF2A12',
    borderRadius: 8,
    borderColor: 'rgba(250, 0, 0, 0.2)',
  },
  ContinueButtonTextStyle: {
    fontSize: 30,
    color: 'black',
  },
  TheEndTextStyle: {
    color: 'black',
    fontSize: 30,
  },
});
